steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=europe-west1-docker.pkg.dev/$PROJECT_ID/default/bike-rental-demo-london
  - --cache=true
  - --cache-ttl=24h
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: gcloud
  args: ['run', 'deploy', 'bike-rental-demo-london', 
  '--image', 'europe-west1-docker.pkg.dev/$PROJECT_ID/default/bike-rental-demo-london', '--region', 'europe-west1', '--service-account', 'bike-rental-service@$PROJECT_ID.iam.gserviceaccount.com', '--allow-unauthenticated', '--set-env-vars=MAPS_KEY=$_MAPS_KEY,PROJECT_ID=$PROJECT_ID']
options:
  machineType: 'E2_HIGHCPU_8'
timeout: 300s